export const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN"
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS"
export const GET_FILTER_BEGIN = "GET_FILTER_BEGIN"
export const GET_FILTER_SUCESS = "GET_FILTER_SUCESS"